### ISSUE TITLE
Only getting 200 users

### ISSUE THREAD

**Issue by Meatwad** [ajhstn/okta-tools#1]
Just tried this code on my Okta instance, and it tops out at 200 users, even though there are 349 in my Okta instance.  Posting issue here per Andrew's suggestion to help evaluate problem.   I am Juan Pescador on the Okta forum :)

**Comment by adrwh** [comment]
Hey @Meatwad i'm guessing your `$result.Headers.Link` is returning a slightly different format, and so retrieving the next url link is failing.

can you send the results of these three lines?
Note:  exclude or anonymise $result.content so that we don't see your PI.
```
$result
$next = (($result.Headers.Link -split "`n")[1] -replace "[\<\>]" -split ";")[0]
$url = $next
```

**Comment by Meatwad** [comment]
Not sure exactly how/when to grab that, but I put a breakpoint in there and was able to get the $result.headers.link shown below:

$result.headers.link
<https://xxxxx.okta.com/api/v1/users?limit=200>; rel="self",<https://xxxxx.okta.com/api/v1/users?after=200ujyf9jvwLWj6CDC0x7&limit=200>; rel="next"

$next and $url are both null

I put a counter inside that do...while loop and it only executes one time, which makes sense I guess if $next and $url are both null after first run through?

Not sure if that's helpful or not?

**Comment by adrwh** [comment]
The `$next` variable in my code expects `$result.Headers.Link` to be a multi-line string array with two objects, split by the new line character.  It looks like your's is split with a `,` comma character. 

eg
```Powershell
[DBG]: PS /Users/a/Okta> $result.Headers.Link
<https://domain.okta.com/api/v1/users?limit=200&filter=status+eq+%22ACTIVE%22>; rel="self"
<https://domain.okta.com/api/v1/users?after=00u5nc9y58MmA8DEb1t7&limit=200&filter=status+eq+%22ACTIVE%22>; rel="next"
[DBG]: PS /Users/a/Okta>
```

Based on your `result.Headers.Link` above, modify the `$next` line to read `$next = (($result -split ',')[1] -split ";")[0]`

**Comment by Meatwad** [comment]
Hi Andrew,

I made that change but it still only returns 200 users...

Thanks!

**Comment by adrwh** [comment]
Hey mate, sorry for the delays.. can you send me results of `$next and $result.Headers.Link` please?

I want to help!

**Comment by Meatwad** [comment]
I think part of the problem is this:

Based on your `result.Headers.Link` above, modify the `$next` line to read `$next = (($result -split ',')[1] -split ";")[0]`

I think you meant to change it to the following (with .headers.link after the $result)

$next = (($result.headers.link -split ',')[1] -split ";")[0]

In any case after lots of trial and error, the below code works.  I had to modify the while statement to remove the [1], and modify the $next= to the third try in there.  Now I get all my users.  

Thanks!


do {
    $result = Invoke-WebRequest -Uri $url -Headers $header -UseBasicParsing
    $json = $result.Content | convertfrom-json
    $Users += $json
    #$next = (($result.Headers.Link -split "`n")[1] -replace "[\<\>]" -split ";")[0]
    #$next = (($result.headers.link -split ',')[1] -split ";")[0]
    $next = (($result.headers.link -split ',')[1] -replace "[\<\>]"-split ";")[0]
    $url = $next

}
while ($result.Headers.Link -match "next")

**Comment by adrwh** [comment]
Hey excellent work, I’m glad you worked it out :)
